DROP TABLE IF EXISTS baskets;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS wishlist;

DROP TABLE IF EXISTS media;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS users;
