DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS saves;

DROP TABLE IF EXISTS wishlist;

DROP TABLE IF EXISTS stars;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS media;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS users;
