version: '3.8'

services:

  migrate:
    image: migrate/migrate
    networks:
      - store
    volumes:
      - ./api-gateway/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@postgres:5432/clothes_store?sslmode=disable", "up" ]
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: clothes_store
    volumes:
      - db:/databasedatadb/postgres
    ports:
      - "5332:5332"
    networks:
      - store
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "1111:1111"
    networks:
      - store
    
  product-service:
    container_name: product-service
    build: ./product-service
    depends_on:
      - user-service
    ports:
      - "3333:3333"
    networks:
      - store
  
  media-service:
    container_name: media-service
    build: ./media-service
    depends_on:
      - user-service
      - product-service
    ports:
      - "2222:2222"
    networks:
      - store
  
  redisdb:
    container_name: redisdb
    image: redis 
    ports:
      - "6378:6378"
    networks:
      - store

  api:
    container_name: api
    build: ./api-gateway
    depends_on:
      - redisdb
      - user-service
      - product-service
      - media-service
    ports:
      - "5555:5555"
    networks:
      - store

networks:
  store:
    driver: bridge

volumes:
  db:
