version: '3.8'

services:

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "1111:1111"
    networks:
      - csm
    
  product-service:
    container_name: product-service
    build: ./product-service
    depends_on:
      - user-service
    ports:
      - "3333:3333"
    networks:
      - csm
  
  media-service:
    container_name: media-service
    build: ./media-service
    depends_on:
      - user-service
      - product-service
    ports:
      - "2222:2222"
    networks:
      - csm
  
  payment-service:
    container_name: payment-service
    build: ./payment-service
    depends_on:
      - user-service
      - product-service
      - media-service
    ports:
      - "4444:4444"
    networks:
      - csm
  
  redisdb:
    container_name: redisdb
    image: redis 
    ports:
      - "6379:6379"
    networks:
      - csm

  api:
    container_name: api
    build: ./api-gateway
    depends_on:
      - redisdb
      - user-service
      - product-service
      - media-service
      - payment-service
    ports:
      - "4444:4444"
    networks:
      - csm

networks:
  csm:
    driver: bridge
