version: '3.8'

services:

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - "1111:1111"
    networks:
      - store
    
  product-service:
    container_name: product-service
    build: ./product-service
    depends_on:
      - user-service
    ports:
      - "3333:3333"
    networks:
      - store
  
  media-service:
    container_name: media-service
    build: ./media-service
    depends_on:
      - user-service
      - product-service
    ports:
      - "2222:2222"
    networks:
      - store
  
  redisdb:
    container_name: redisdb
    image: redis 
    ports:
      - "6378:6378"
    networks:
      - store

  api:
    container_name: api
    build: ./api-gateway
    depends_on:
      - redisdb
      - user-service
      - product-service
      - media-service
    ports:
      - "5555:5555"
    networks:
      - store

networks:
  store:
    driver: bridge
