version: '3.8'

services:

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - store
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=abdulaziz
      - MINIO_ROOT_PASSWORD=abdulaziz
      - MINIO_DEFAULT_BUCKETS=clothesstore

  migrate:
    image: migrate/migrate
    networks:
      - store
    volumes:
      - ./api-gateway/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@clothes-postgres:5432/clothes_store?sslmode=disable", "up" ]
    depends_on:
      - postgres-db

  postgres-db:
    container_name: clothes-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: clothes_store
    volumes:
      - db:/databasedatadb/postgres
    ports:
      - "5331:5331"
    networks:
      - store
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  user-service:
    container_name: clothes-user-service
    build: ./user-service
    ports:
      - "1111:1111"
    depends_on:
      - postgres-db
    networks:
      - store
    
  product-service:
    container_name: clothes-product-service
    build: ./product-service
    depends_on:
      - user-service
      - postgres-db
    ports:
      - "3333:3333"
    networks:
      - store
  
  media-service:
    container_name: clothes-media-service
    build: ./media-service
    depends_on:
      - user-service
      - product-service
      - postgres-db
    ports:
      - "2222:2222"
    networks:
      - store
  
  redis-db:
    container_name: clothes-redis-db
    image: redis 
    ports:
      - "6377:6377"
    networks:
      - store

  api:
    container_name: clothes-api
    build: ./api-gateway
    depends_on:
      - redis-db
      - user-service
      - product-service
      - media-service
      - postgres-db
    ports:
      - "5555:5555"
    networks:
      - store

networks:
  store:
    driver: bridge

volumes:
  db:
  minio_data:
    driver: local
