CREATE TABLE IF NOT EXISTS USERS(
    ID UUID PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    GENDER TEXT NOT NULL,
    AGE INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

INSERT INTO users(id, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, PHONE_NUMBER, GENDER, AGE) VALUES(
    '5623ea51-e785-42a6-b2fc-ec5c231043c6', 'a','a','a','a','a','a',21
);