CREATE TABLE IF NOT EXISTS STARS(
    ID UUID PRIMARY KEY,
    PRODUCT_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    STAR INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (id)
);