// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: product_service.proto

package product_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("product_service.proto", fileDescriptor_64a1a24e6b7d7ed5) }

var fileDescriptor_64a1a24e6b7d7ed5 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdf, 0x6e, 0x52, 0x41,
	0x10, 0xc6, 0xe5, 0xc6, 0xd4, 0xa1, 0x1c, 0xcd, 0x36, 0xb5, 0xf5, 0xc4, 0x9e, 0x78, 0xed, 0x45,
	0x4d, 0xf4, 0xde, 0x44, 0x40, 0x97, 0x2a, 0x54, 0x04, 0x49, 0x13, 0x6f, 0xcc, 0x16, 0x26, 0x65,
	0x03, 0x65, 0x61, 0x77, 0x21, 0xe9, 0xbd, 0x0f, 0xe1, 0x23, 0x79, 0xe9, 0x23, 0x18, 0x7c, 0x11,
	0xc3, 0x19, 0x16, 0x09, 0x7b, 0xfe, 0x90, 0x9c, 0x5e, 0x32, 0xf3, 0xed, 0x6f, 0x67, 0xe7, 0x9b,
	0xe1, 0xc0, 0xf1, 0x54, 0xab, 0xc1, 0xbc, 0x6f, 0xbf, 0x1b, 0xd4, 0x0b, 0xd9, 0xc7, 0xf3, 0xa9,
	0x56, 0x56, 0xb1, 0xc7, 0x3b, 0xe1, 0xf0, 0xc8, 0x05, 0x6e, 0xd5, 0x00, 0xc7, 0xa4, 0x7a, 0xfd,
	0x23, 0x80, 0xa0, 0x4d, 0xf1, 0x2e, 0xe9, 0xd8, 0x07, 0x08, 0x6a, 0x1a, 0x85, 0xc5, 0x9a, 0xb0,
	0x78, 0xa3, 0xf4, 0x1d, 0x7b, 0x76, 0xbe, 0x7b, 0x85, 0x4b, 0x85, 0xe9, 0x29, 0xf6, 0x09, 0x82,
	0x3a, 0x8e, 0x71, 0x8b, 0x13, 0x7a, 0x62, 0x8e, 0xf6, 0x4a, 0xda, 0xe1, 0x45, 0x3d, 0x3c, 0xf3,
	0x72, 0x2d, 0xb5, 0xc0, 0x0e, 0x9a, 0xa9, 0x9a, 0x98, 0xb8, 0xa8, 0xde, 0x74, 0x50, 0xbc, 0xa8,
	0x3a, 0x94, 0x39, 0xda, 0xbd, 0x2a, 0xca, 0xa0, 0xb4, 0x20, 0x68, 0x4a, 0xe3, 0x30, 0x12, 0x0d,
	0x7b, 0xee, 0x89, 0x57, 0x82, 0x0e, 0xce, 0xe6, 0x68, 0x6c, 0xc2, 0xe3, 0xb6, 0x8e, 0xdf, 0xb1,
	0x4b, 0x08, 0xba, 0x28, 0x74, 0x7f, 0xb8, 0x89, 0x44, 0xde, 0x01, 0x12, 0x38, 0x60, 0xf2, 0x75,
	0x6b, 0x23, 0x59, 0x03, 0x82, 0xde, 0x44, 0xce, 0xe6, 0xff, 0x9b, 0x75, 0xe2, 0xe9, 0xdb, 0x42,
	0x8b, 0x5b, 0x93, 0xd7, 0xf6, 0xf7, 0x50, 0xa1, 0x59, 0x70, 0xe8, 0x53, 0x1f, 0x44, 0xbf, 0xc3,
	0x8c, 0x56, 0xb2, 0x1a, 0x54, 0xc8, 0xbd, 0x7c, 0x4c, 0x6a, 0x86, 0x7d, 0x84, 0x0a, 0xcd, 0x93,
	0x0b, 0x14, 0x18, 0xa7, 0x2a, 0x00, 0x47, 0xbb, 0x0f, 0x28, 0xab, 0x9e, 0xc3, 0xad, 0xa6, 0xe7,
	0x8d, 0x40, 0xb6, 0x63, 0x2d, 0xa8, 0x90, 0xc1, 0x2e, 0x50, 0x6c, 0x00, 0xbe, 0xc0, 0x11, 0x47,
	0x5b, 0x97, 0xa6, 0xaf, 0xe6, 0x93, 0xfb, 0xa9, 0xf0, 0x12, 0x18, 0x21, 0xc5, 0xf5, 0x18, 0xf7,
	0x24, 0x86, 0x89, 0xd9, 0xcf, 0x7a, 0x80, 0x9a, 0xd5, 0xa0, 0xdc, 0x94, 0xa3, 0x8d, 0x97, 0xc7,
	0x09, 0xd2, 0x11, 0xe6, 0xd9, 0xd8, 0x84, 0xc3, 0x9e, 0x41, 0x7d, 0x25, 0xcd, 0x70, 0x2c, 0x4d,
	0xd1, 0xae, 0x71, 0x38, 0xb8, 0x30, 0xb4, 0x38, 0x09, 0x0f, 0x73, 0xa9, 0x0e, 0xce, 0xf6, 0x28,
	0xab, 0x2b, 0x16, 0xf8, 0x55, 0x55, 0x85, 0x19, 0xa1, 0x65, 0x2f, 0x3c, 0x39, 0x25, 0x68, 0xb5,
	0x56, 0xc0, 0xec, 0xe5, 0x79, 0xc4, 0xd1, 0xae, 0x51, 0x67, 0x29, 0x28, 0x8e, 0xab, 0xae, 0x87,
	0x27, 0x29, 0x69, 0xf6, 0x0e, 0xca, 0x74, 0x1b, 0x75, 0xff, 0xa9, 0xa7, 0x8b, 0xe3, 0x99, 0x75,
	0xbc, 0x85, 0x03, 0x8e, 0x6b, 0xf7, 0xb2, 0x36, 0x26, 0x85, 0xcd, 0x1a, 0x50, 0xa6, 0xfd, 0xcd,
	0x47, 0xe4, 0xf4, 0xb7, 0x0d, 0x4f, 0x56, 0xb6, 0xc7, 0x9c, 0x86, 0x34, 0xb6, 0xf0, 0x3f, 0x66,
	0xf5, 0xe5, 0xaf, 0x65, 0x54, 0xfa, 0xbd, 0x8c, 0x4a, 0x7f, 0x96, 0x51, 0xe9, 0xe7, 0xdf, 0xe8,
	0xc1, 0xb7, 0xd3, 0x1b, 0x9c, 0xc4, 0x9f, 0xc8, 0x57, 0x3b, 0xe7, 0xae, 0x1f, 0xc6, 0xe1, 0x37,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0x94, 0xc5, 0xd8, 0x78, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	CreateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*Category, error)
	DeleteCategory(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*MoveResponse, error)
	UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*Category, error)
	GetCategory(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*Category, error)
	ListCategories(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListCategory, error)
	SearchCategory(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error)
	UniqueCategory(ctx context.Context, in *Params, opts ...grpc.CallOption) (*MoveResponse, error)
	CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*GetWithID, error)
	UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	DeleteProduct(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*MoveResponse, error)
	GetProduct(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*Product, error)
	ListProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProduct, error)
	SearchProduct(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error)
	GetDiscountProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProduct, error)
	GetDisableProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListOrder, error)
	LikeProduct(ctx context.Context, in *Like, opts ...grpc.CallOption) (*MoveResponse, error)
	UserWishlist(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error)
	IsUnique(ctx context.Context, in *IsUniqueReq, opts ...grpc.CallOption) (*MoveResponse, error)
	SaveToBasket(ctx context.Context, in *BasketCreateReq, opts ...grpc.CallOption) (*GetWithID, error)
	GetBasket(ctx context.Context, in *BasketGetReq, opts ...grpc.CallOption) (*Basket, error)
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*GetWithID, error)
	GetOrder(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*Order, error)
	DeleteOrder(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*MoveResponse, error)
	UserOrderHistory(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteCategory(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/DeleteCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCategory(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListCategories(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListCategory, error) {
	out := new(ListCategory)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SearchCategory(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error) {
	out := new(ListProduct)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/SearchCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UniqueCategory(ctx context.Context, in *Params, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/UniqueCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*GetWithID, error) {
	out := new(GetWithID)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProduct, error) {
	out := new(ListProduct)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SearchProduct(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error) {
	out := new(ListProduct)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/SearchProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetDiscountProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProduct, error) {
	out := new(ListProduct)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/GetDiscountProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetDisableProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListOrder, error) {
	out := new(ListOrder)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/GetDisableProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) LikeProduct(ctx context.Context, in *Like, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/LikeProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UserWishlist(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error) {
	out := new(ListProduct)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/UserWishlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) IsUnique(ctx context.Context, in *IsUniqueReq, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/IsUnique", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveToBasket(ctx context.Context, in *BasketCreateReq, opts ...grpc.CallOption) (*GetWithID, error) {
	out := new(GetWithID)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/SaveToBasket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetBasket(ctx context.Context, in *BasketGetReq, opts ...grpc.CallOption) (*Basket, error) {
	out := new(Basket)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/GetBasket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*GetWithID, error) {
	out := new(GetWithID)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetOrder(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteOrder(ctx context.Context, in *GetWithID, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UserOrderHistory(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ListProduct, error) {
	out := new(ListProduct)
	err := c.cc.Invoke(ctx, "/product_service.ProductService/UserOrderHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	CreateCategory(context.Context, *Category) (*Category, error)
	DeleteCategory(context.Context, *GetWithID) (*MoveResponse, error)
	UpdateCategory(context.Context, *Category) (*Category, error)
	GetCategory(context.Context, *GetWithID) (*Category, error)
	ListCategories(context.Context, *ListRequest) (*ListCategory, error)
	SearchCategory(context.Context, *SearchRequest) (*ListProduct, error)
	UniqueCategory(context.Context, *Params) (*MoveResponse, error)
	CreateProduct(context.Context, *Product) (*GetWithID, error)
	UpdateProduct(context.Context, *Product) (*Product, error)
	DeleteProduct(context.Context, *GetWithID) (*MoveResponse, error)
	GetProduct(context.Context, *GetWithID) (*Product, error)
	ListProducts(context.Context, *ListRequest) (*ListProduct, error)
	SearchProduct(context.Context, *SearchRequest) (*ListProduct, error)
	GetDiscountProducts(context.Context, *ListRequest) (*ListProduct, error)
	GetDisableProducts(context.Context, *ListRequest) (*ListOrder, error)
	LikeProduct(context.Context, *Like) (*MoveResponse, error)
	UserWishlist(context.Context, *SearchRequest) (*ListProduct, error)
	IsUnique(context.Context, *IsUniqueReq) (*MoveResponse, error)
	SaveToBasket(context.Context, *BasketCreateReq) (*GetWithID, error)
	GetBasket(context.Context, *BasketGetReq) (*Basket, error)
	CreateOrder(context.Context, *Order) (*GetWithID, error)
	GetOrder(context.Context, *GetWithID) (*Order, error)
	DeleteOrder(context.Context, *GetWithID) (*MoveResponse, error)
	UserOrderHistory(context.Context, *SearchRequest) (*ListProduct, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) CreateCategory(ctx context.Context, req *Category) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (*UnimplementedProductServiceServer) DeleteCategory(ctx context.Context, req *GetWithID) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (*UnimplementedProductServiceServer) UpdateCategory(ctx context.Context, req *Category) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (*UnimplementedProductServiceServer) GetCategory(ctx context.Context, req *GetWithID) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}
func (*UnimplementedProductServiceServer) ListCategories(ctx context.Context, req *ListRequest) (*ListCategory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (*UnimplementedProductServiceServer) SearchCategory(ctx context.Context, req *SearchRequest) (*ListProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCategory not implemented")
}
func (*UnimplementedProductServiceServer) UniqueCategory(ctx context.Context, req *Params) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniqueCategory not implemented")
}
func (*UnimplementedProductServiceServer) CreateProduct(ctx context.Context, req *Product) (*GetWithID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedProductServiceServer) UpdateProduct(ctx context.Context, req *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProduct(ctx context.Context, req *GetWithID) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProduct(ctx context.Context, req *GetWithID) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedProductServiceServer) ListProducts(ctx context.Context, req *ListRequest) (*ListProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (*UnimplementedProductServiceServer) SearchProduct(ctx context.Context, req *SearchRequest) (*ListProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetDiscountProducts(ctx context.Context, req *ListRequest) (*ListProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscountProducts not implemented")
}
func (*UnimplementedProductServiceServer) GetDisableProducts(ctx context.Context, req *ListRequest) (*ListOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDisableProducts not implemented")
}
func (*UnimplementedProductServiceServer) LikeProduct(ctx context.Context, req *Like) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeProduct not implemented")
}
func (*UnimplementedProductServiceServer) UserWishlist(ctx context.Context, req *SearchRequest) (*ListProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserWishlist not implemented")
}
func (*UnimplementedProductServiceServer) IsUnique(ctx context.Context, req *IsUniqueReq) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUnique not implemented")
}
func (*UnimplementedProductServiceServer) SaveToBasket(ctx context.Context, req *BasketCreateReq) (*GetWithID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveToBasket not implemented")
}
func (*UnimplementedProductServiceServer) GetBasket(ctx context.Context, req *BasketGetReq) (*Basket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasket not implemented")
}
func (*UnimplementedProductServiceServer) CreateOrder(ctx context.Context, req *Order) (*GetWithID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedProductServiceServer) GetOrder(ctx context.Context, req *GetWithID) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (*UnimplementedProductServiceServer) DeleteOrder(ctx context.Context, req *GetWithID) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrder not implemented")
}
func (*UnimplementedProductServiceServer) UserOrderHistory(ctx context.Context, req *SearchRequest) (*ListProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOrderHistory not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/DeleteCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteCategory(ctx, req.(*GetWithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCategory(ctx, req.(*GetWithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListCategories(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SearchCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SearchCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/SearchCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SearchCategory(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UniqueCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UniqueCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/UniqueCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UniqueCategory(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*GetWithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetWithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProducts(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SearchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SearchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/SearchProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SearchProduct(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetDiscountProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetDiscountProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/GetDiscountProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetDiscountProducts(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetDisableProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetDisableProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/GetDisableProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetDisableProducts(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_LikeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).LikeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/LikeProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).LikeProduct(ctx, req.(*Like))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UserWishlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UserWishlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/UserWishlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UserWishlist(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_IsUnique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUniqueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).IsUnique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/IsUnique",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).IsUnique(ctx, req.(*IsUniqueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveToBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasketCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveToBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/SaveToBasket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveToBasket(ctx, req.(*BasketCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasketGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/GetBasket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetBasket(ctx, req.(*BasketGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetOrder(ctx, req.(*GetWithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteOrder(ctx, req.(*GetWithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UserOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UserOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product_service.ProductService/UserOrderHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UserOrderHistory(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product_service.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _ProductService_CreateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _ProductService_DeleteCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ProductService_UpdateCategory_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ProductService_GetCategory_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _ProductService_ListCategories_Handler,
		},
		{
			MethodName: "SearchCategory",
			Handler:    _ProductService_SearchCategory_Handler,
		},
		{
			MethodName: "UniqueCategory",
			Handler:    _ProductService_UniqueCategory_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductService_ListProducts_Handler,
		},
		{
			MethodName: "SearchProduct",
			Handler:    _ProductService_SearchProduct_Handler,
		},
		{
			MethodName: "GetDiscountProducts",
			Handler:    _ProductService_GetDiscountProducts_Handler,
		},
		{
			MethodName: "GetDisableProducts",
			Handler:    _ProductService_GetDisableProducts_Handler,
		},
		{
			MethodName: "LikeProduct",
			Handler:    _ProductService_LikeProduct_Handler,
		},
		{
			MethodName: "UserWishlist",
			Handler:    _ProductService_UserWishlist_Handler,
		},
		{
			MethodName: "IsUnique",
			Handler:    _ProductService_IsUnique_Handler,
		},
		{
			MethodName: "SaveToBasket",
			Handler:    _ProductService_SaveToBasket_Handler,
		},
		{
			MethodName: "GetBasket",
			Handler:    _ProductService_GetBasket_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _ProductService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _ProductService_GetOrder_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _ProductService_DeleteOrder_Handler,
		},
		{
			MethodName: "UserOrderHistory",
			Handler:    _ProductService_UserOrderHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_service.proto",
}
